export default [
	{
		id: Math.random().toString(),
		title: 'New York',
		image: '',
		address: 'New York 10',
		price: 1000,
		numOfGuests: 2,
		numOfBeds: 3,
		numOfBaths: 2,
		rating: 4,
	},
	{
		id: Math.random().toString(),
		title: 'Los Angeles',
		image: '',
		address: 'Los Angeles 120',
		price: 1023,
		numOfGuests: 2,
		numOfBeds: 1,
		numOfBaths: 3,
		rating: 5,
	},
	{
		id: Math.random().toString(),
		title: 'Yerevan',
		image: '',
		address: 'Tichina 3',
		price: 250,
		numOfGuests: 6,
		numOfBeds: 3,
		numOfBaths: 2,
		rating: 3,
	},
	{
		id: Math.random().toString(),
		title: 'Moscow',
		image: '',
		address: 'Moscow 334',
		price: 2050,
		numOfGuests: 1,
		numOfBeds: 1,
		numOfBaths: 2,
		rating: 4,
	},
]
